plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

remote_theme: kosatyi/sjt

navigation: false
projects: true


baseurl: /gulp2go

brand: gulp2go
title: Gulp2Go
description: Gulp bundler for javascript scss and svg files
analytics: UA-37629144-1
adsense: ca-pub-3650650669153101

author:
  name: Stepan Kosatyi
  url: https://kosatyi.com/


